package RecapWithAhmet;

public class Contructor {

    // what is a constructor and what do you do with it?
    //can you tell me the difference between constuctor and method
    //can you make the constructor private

    //!!!!!! go from general to deep

    //IS A WAY TO INITIALIZE INSTANCE VARIABLE
    //WE HAVE SPECIFIC FEATURES FOR THE COSTRUCTOR
    //1.IT MUST HAVE THE SAME NAME AS THE CLASS
    //2.IT DOESN'T HAVE RETURN TYPE
    //----> AGAIN WE NEED IT TO INITIALIZE4 OUR ISNT VARIB



    //1.METHOD HAS RETURN TYPE
    //2.CAN HAVE SAME OR DIFFERENT REFERENCE NAME
    //
    //!!!YES WE CAN MAKE THE CONSTRUCTOR PRIVATE FOR THE SINGLETON PATTERN DESIGN--IT IS A SPECIAL CLASS THAT
    //THAT DO NOT LET YOU CREATE AN OBJECT

    //WHATIS THE DIFFERENCE BETWEEN, THIS AND SUPER
    //THIS IS A KEYWORD TO CALL THE VARIBLES OR METHODS WHICH BELONG TO THE SAME CLASS


    //SUPER--> IS A KEYWORD TO CALL THE VARIBLES AND METHODS WHICH CALL THE PARENT CLASS

    ///TSUPER()---> IS A,METHOD TO CALL THE CONSTRUCTOR WHICH BELONGS TO THE PARENT CLASS
    //    //---> MUST BE AT THE FIRST LINE OF THE CONSTRUCTOR







}
